### PR TITLE
added nvidia nemo diarization model

### LINKED ISSUE #327: Task: add nemo diarization
### Description

Add the nemo toolkit based diarization

### Tasks

- [x] add nemo as a dependency
- [x] add nemo based routines to relevant modules.

### Freeform Notes

_No response_

### PR DESCRIPTION
**Pull request by fabiocat93**
## Description
Added the nemo toolkit based diarization.
@900miles I know this was on you, but this is urgent for some work in the lab (@yibeichan and more folks), hence I have implemented a first integration. Feel free to review it/improve it once you will have the time

## Related Issue(s)
https://github.com/sensein/senselab/issues/327

## How Has This Been Tested?
Unit tests

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by 900miles** [comment]
Thanks @fabiocat93 ! I'll give it a review.

File: src/senselab/audio/tasks/speaker_diarization/nvidia.py [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmpfile:
+            tmpfile_path = tmpfile.name
+        try:
+            audio.save_to_file(tmpfile_path)
+            diarization_segments = model.diarize(audio=tmpfile_path)
+            # diarization_segments: List[List[str]], e.g. [['0.080 4.950 speaker_0']]
+            script_lines: List[ScriptLine] = []
+            for seg in diarization_segments:
+                # seg: List[str], e.g. '[0.080 4.950 speaker_0]'
+                parts = seg[0].strip().split()
```
Comment (900miles) [inline src/senselab/audio/tasks/speaker_diarization/nvidia.py]: I was getting a weird result that only the first speaker segment was being returned. I tracked it down to this line. At this point, seg looks something like this:

```
['0.160 4.640 speaker_0', '69.440 70.080 speaker_0', '70.400 71.120 speaker_0', '113.280 116.720 speaker_0', '4.720 20.480 speaker_1', '20.640 20.800 speaker_1', '20.880 41.200 speaker_1', '41.280 59.440 speaker_1', '60.080 65.920 speaker_1', '66.240 69.280 speaker_1', '104.080 105.840 speaker_1', '107.440 107.760 speaker_1', '109.440 109.840 speaker_1', '111.200 115.200 speaker_1', '115.680 117.520 speaker_1', '71.760 77.040 speaker_2', '78.320 80.240 speaker_2', '81.040 94.480 speaker_2', '94.560 95.280 speaker_2', '95.680 100.400 speaker_2', '101.280 102.320 speaker_2', '106.080 107.440 speaker_2', '108.080 109.440 speaker_2', '109.840 111.920 speaker_2', '118.000 139.680 speaker_3']
```

i.e. a list of strings of speaker segments. So taking `seg[0]` will only get the first segment!

File: tutorials/audio/speaker_diarization.ipynb [hunk 2]
```diff
@@ -100,11 +103,38 @@
                 "\n",
                 "Unfortunately, the model is not perfect and can make mistakes. We can try adjusting the parameters by setting `num_speakers=4`, `min_speakers=4`, and `max_speakers=4` to force the model to recognize four speakers. However, this approach doesn't always work as expected."
             ]
+        },
+        {
+            "cell_type": "markdown",
+            "metadata": {},
+            "source": [
+                "And let's say we want to try with a cool NVIDIA nemo model, we can do the following:"
```
Comment (900miles) [inline tutorials/audio/speaker_diarization.ipynb:111]: Somewhere (maybe here? Maybe in doc.md) we should note the sortformer limitation that: `It can detect a maximum of 4 speakers; performance degrades on recordings with 5 and more speakers.`

**Review by 900miles — CHANGES_REQUESTED** [review]

File: src/senselab/audio/tasks/speaker_diarization/nvidia.py (hunk 1 above)
Comment (fabiocat93) [reply src/senselab/audio/tasks/speaker_diarization/nvidia.py]: solved. I have also noticed it when worked with @yibeichan 's Friends episode :)

File: tutorials/audio/speaker_diarization.ipynb (hunk 2 above)
Comment (fabiocat93) [reply tutorials/audio/speaker_diarization.ipynb:111]: Good point! I have also already noted that. I have realized of this limitation after working with Friends video clips, which include way more characters

**Comment by fabiocat93** [comment]
**Blocker:**
- mediapipe doesn't work with protobuf 3.20.3. This is the error we see after running `poetry run pytest src/tests/video/tasks/pose_estimation_test.py`: `FAILED src/tests/video/tasks/pose_estimation_test.py::test_visualize_pose[sample_pose_mediapipe] - AttributeError: 'FieldDescriptor' object has no attribute '_default_constructor'`
- The published nemo-toolkit 2.2.1 on PyPI requires protobuf 3.20.3 (see: [](https://pypi.org/project/nemo-toolkit/2.2.1/)<https://pypi.org/project/nemo-toolkit/2.2.1/>).
- The source repo has updated requirements (!!!), but until a new version is published, we cannot use it

We will need to wait until the nvidia team will release a version of nemo-toolkit with updated requirements (as in their main branch)

**Comment by satra** [comment]
just fyi: pypi has nemo 2.3.0 released on may 8.

File: pyproject.toml [hunk 3]
```diff
@@ -67,6 +67,7 @@ mediapipe = {version = "~=0.10", optional = true}
 opencv-python = {version = "~=4.10", optional = true}
 ultralytics = {version = "~=8.3", optional = true}
 av = {version = "~=14.2", optional = true}
+nemo-toolkit = {version = "2.2.1", optional = true, extras = ["asr"]}
```
Comment (satra) [inline pyproject.toml]:
```suggestion
nemo-toolkit = {version = "2.3.0", optional = true, extras = ["asr"]}
```

**Comment by satra** [comment]
still an issue:

> And because mediapipe (0.10.15) depends on protobuf (>=4.25.3,<5)
 and nemo-toolkit[asr] (2.3.0) depends on protobuf (4.24.4), nemo-toolkit[asr] (2.3.0) is incompatible with mediapipe (>=0.10,<1.0).
 
 i'll file with nemo-toolkit to see if they can relax the exact match that they have.

**Comment by satra** [comment]
filed here: https://github.com/NVIDIA/NeMo/issues/13721

**Comment by fabiocat93** [comment]
> filed here: [NVIDIA/NeMo#13721](https://github.com/NVIDIA/NeMo/issues/13721)

FYI, they tried to soften the dependencies by switching to protobuf~=4.24.4, but that's still not enough for our use case (mediapipe requires protobuf>=4.25.3,<5, so the conflict remains)

**Comment by fabiocat93** [comment]
> > filed here: [NVIDIA/NeMo#13721](https://github.com/NVIDIA/NeMo/issues/13721)
> 
> FYI, they tried to soften the dependencies by switching to protobuf~=4.24.4, but that's still not enough for our use case (mediapipe requires protobuf>=4.25.3,<5, so the conflict remains)

NeMo now requires protobuf v5, which is not supported by mediapipe. it really seems that containerizing mediapipe is the solution to go

**Comment by satra** [comment]
> it really seems that containerizing mediapipe is the solution to go

containerized execution (whether virtual environments or actual containers) are likely to be needed for many interfaces. we can discuss this today.
